# Generated by Django 4.0.3 on 2022-04-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temprature', models.CharField(max_length=200)),
                ('time_stamp', models.DateField(auto_now_add=True)),
                ('wather_name', models.CharField(max_length=100)),
            ],
        ),
    ]
